name: deeprlstocktrading
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - numpy
  - pandas
  - tensorboardx
  - termcolor
  - torchvision
  - pytorch
  - cudatoolkit=10.2
  - torchaudio
  - notebook
  - matplotlib
  - seaborn
  - quantstats
  - pip
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - beautifulsoup4==4.10.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.8
    - cvxpy==1.1.18
    - dataframe-image==0.1.1
    - ecos==2.0.10
    - empyrical==0.5.5
    - frozenlist==1.2.0
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - joblib==1.1.0
    - markdown==3.3.6
    - multidict==5.2.0
    - oauthlib==3.1.1
    - osqp==0.6.2.post4
    - pandas-datareader==0.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfolio==0.9.2+75.g4b901f6
    - pyportfolioopt==1.5.1
    - qdldl==0.1.5.post0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - scikit-learn==1.0.2
    - scs==3.0.1
    - soupsieve==2.3.1
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==3.0.0
    - urllib3==1.26.7
    - werkzeug==2.0.2
    - yarl==1.7.2
